// Permission mapping for all menu items using new database-driven permission system
export const PERMISSION_MAP: Record<string, string[]> = {
  '/dashboard': ['dashboard:view'],
  '/dashboard/schools': ['schools:view'],
  '/dashboard/students': ['students:view'],
  '/dashboard/classes': ['classes:view'],
  '/dashboard/vehicles': ['vehicles:view'],
  '/dashboard/drivers': ['drivers:view'],
  '/dashboard/raw-materials': ['raw_materials:view'],
  '/dashboard/suppliers': ['suppliers:view'],
  '/dashboard/purchase-orders': ['purchase_orders:view'],
  '/dashboard/purchase-orders/analytics': ['purchase_orders:view'],
  '/dashboard/inventory': ['inventory:view'],
  '/dashboard/distribution': ['distribution:view'],
  '/dashboard/distributions': ['distribution:view'],
  '/dashboard/distributions/schools': ['distribution:view'],
  '/dashboard/distributions/tracking': ['distribution:view'],
  '/dashboard/distributions/routes': ['distribution:view'],
  '/dashboard/distribution/create': ['distribution:create'],
  '/dashboard/deliveries': ['distribution:view'],
  '/dashboard/delivery-tracking': ['distribution:view'],
  '/dashboard/recipes': ['recipes:view'],
  '/dashboard/recipes/new': ['recipes:create'],
  '/dashboard/menu-planning': ['menu_planning:view'],
  '/dashboard/menu-planning/create': ['menu_planning:create'],
  '/dashboard/menu-planning/ai-planner': ['menu_planning:create'],
  '/dashboard/menu-planning/nutrition': ['menu_planning:view'],
  '/dashboard/menu-planning/planning': ['menu_planning:view'],
  '/dashboard/production': ['production_batches:view'],
  '/dashboard/production/batches': ['production_batches:view'],
  '/dashboard/production/batches/new': ['production_batches:create'],
  '/dashboard/production/batches/from-recipe': ['production_batches:create'],
  '/dashboard/production/resources': ['production_resources:view'],
  '/dashboard/production/resources/add': ['production_resources:create'],
  '/dashboard/production/resources/inventory': ['production_resources:view'],
  '/dashboard/production/resources/maintenance': ['production_resources:view'],
  '/dashboard/production/resources/purchase-order': ['purchase_orders:create'],
  '/dashboard/production/resources/stock-report': ['production_resources:view'],
  '/dashboard/production/quality': ['quality_standards:view'],
  '/dashboard/production/quality/create': ['quality_standards:create'],
  '/dashboard/production/quality/reports': ['quality_checks:view'],
  '/dashboard/production/quality/sop-guidelines': ['quality_standards:view'],
  '/dashboard/production/quality/photo-documentation': ['quality_checks:view'],
  '/dashboard/production/quality/report-issue': ['quality_checks:create'],
  '/dashboard/production/execution': ['production_batches:view'],
  '/dashboard/production/analytics': ['production_batches:view'],
  '/dashboard/production/ai-optimizer': ['production_batches:create'],
  '/dashboard/production-plans': ['production_plans:view'],
  '/dashboard/production-plans/create': ['production_plans:create'],
  '/dashboard/quality': ['quality_standards:view'],
  '/dashboard/quality-standards': ['quality_standards:view'],
  '/dashboard/quality-standards/create': ['quality_standards:create'],
  '/dashboard/quality-checks': ['quality_checks:view'],
  '/dashboard/quality-checks/create': ['quality_checks:create'],
  '/dashboard/quality-checkpoints': ['quality_checkpoints:view'],
  '/dashboard/quality-checkpoints/create': ['quality_checkpoints:create'],
  '/dashboard/food-samples': ['food_samples:view'],
  '/dashboard/food-samples/create': ['food_samples:create'],
  '/dashboard/nutrition-consultations': ['nutrition_consultations:view'],
  '/dashboard/nutrition-consultations/create': ['nutrition_consultations:create'],
  '/dashboard/users': ['users:view'],
  '/dashboard/users/create': ['users:create'],
  '/dashboard/roles': ['roles:view'],
  '/dashboard/roles/create': ['roles:create'],
  '/dashboard/user-roles': ['user_roles:view'],
  '/dashboard/user-roles/create': ['user_roles:create'],
  '/dashboard/notifications': ['notifications:view'],
  '/dashboard/monitoring': ['monitoring:view'],
  '/dashboard/monitoring/real-time': ['monitoring:view'],
  '/dashboard/monitoring/performance': ['monitoring:view'],
  '/dashboard/monitoring/analytics': ['monitoring:view'],
  '/dashboard/monitoring/reports': ['monitoring:view'],
  '/dashboard/analytics': ['analytics:view'],
  '/dashboard/performance': ['performance:view'],
  '/dashboard/financial': ['financial:view'],
  '/dashboard/financial/transactions': ['financial:view'],
  '/dashboard/financial/transactions/create': ['financial:create'],
  '/dashboard/financial/budgets/create': ['financial:create'],
  '/dashboard/feedback': ['feedback:view'],
  '/dashboard/waste-records': ['waste_records:view'],
  '/dashboard/waste-records/create': ['waste_records:create'],
  '/dashboard/items': ['items:view'],
  '/dashboard/items/create': ['items:create'],
  '/dashboard/resource-usage': ['resource_usage:view'],
  '/dashboard/resource-usage/create': ['resource_usage:create'],
  '/dashboard/audit-logs': ['audit_logs:view'],
  '/dashboard/system-config': ['system_config:edit'],
  '/dashboard/admin': ['admin:access'],
  '/dashboard/admin/users': ['users:view'],
  '/dashboard/admin/settings': ['system_config:edit'],
  '/dashboard/admin/security': ['admin:access'],
  '/dashboard/admin/database': ['admin:access'],
  '/dashboard/profile': [] // Always accessible to authenticated users
}

// Helper function to get permissions for a given path
export function getPermissionsForPath(path: string): string[] {
  return PERMISSION_MAP[path] || []
}

// Helper function to check if a path requires specific permissions
export function pathRequiresPermissions(path: string): boolean {
  const permissions = getPermissionsForPath(path)
  return permissions.length > 0
}
