// Permission mapping for all menu items using new database-driven permission system
export const PERMISSION_MAP: Record<string, string[]> = {
  '/dashboard': [], // Dashboard is always accessible to authenticated users
  '/dashboard/schools': ['schools.view'],
  '/dashboard/students': ['students.view'],
  '/dashboard/classes': ['classes.view'],
  '/dashboard/vehicles': ['vehicles.view'],
  '/dashboard/drivers': ['drivers.view'],
  '/dashboard/raw-materials': ['inventory.view'],
  '/dashboard/suppliers': ['suppliers.view'],
  '/dashboard/purchase-orders': ['purchase_orders.view'],
  '/dashboard/purchase-orders/analytics': ['purchase_orders.view'],
  '/dashboard/inventory': ['inventory.view'],
  '/dashboard/distribution': ['distributions.view'],
  '/dashboard/distributions': ['distributions.view'],
  '/dashboard/distributions/schools': ['distributions.view'],
  '/dashboard/distributions/tracking': ['distributions.view'],
  '/dashboard/distributions/routes': ['distributions.view'],
  '/dashboard/distribution/create': ['distributions.create'],
  '/dashboard/deliveries': ['delivery.view'],
  '/dashboard/delivery-tracking': ['delivery.view'],
  '/dashboard/recipes': ['recipes.view'],
  '/dashboard/recipes/new': ['recipes.create'],
  '/dashboard/menu-planning': ['menus.view'],
  '/dashboard/menu-planning/create': ['menus.create'],
  '/dashboard/menu-planning/ai-planner': ['menus.create'],
  '/dashboard/menu-planning/nutrition': ['menus.view'],
  '/dashboard/menu-planning/planning': ['menus.view'],
  '/dashboard/production': ['production.view'],
  '/dashboard/production/batches': ['production.view'],
  '/dashboard/production/batches/new': ['production.create'],
  '/dashboard/production/batches/from-recipe': ['production.create'],
  '/dashboard/production/resources': ['inventory.view'],
  '/dashboard/production/resources/add': ['inventory.create'],
  '/dashboard/production/resources/inventory': ['inventory.view'],
  '/dashboard/production/resources/maintenance': ['inventory.view'],
  '/dashboard/production/resources/purchase-order': ['purchase_orders.create'],
  '/dashboard/production/resources/stock-report': ['inventory.view'],
  '/dashboard/production/quality': ['quality.check'],
  '/dashboard/production/quality/create': ['quality.create'],
  '/dashboard/production/quality/reports': ['quality.check'],
  '/dashboard/production/quality/sop-guidelines': ['quality.check'],
  '/dashboard/production/quality/photo-documentation': ['quality.check'],
  '/dashboard/production/quality/report-issue': ['quality.check'],
  '/dashboard/production/execution': ['production.view'],
  '/dashboard/production/analytics': ['production.view'],
  '/dashboard/production/ai-optimizer': ['production.create'],
  '/dashboard/production-plans': ['production.view'],
  '/dashboard/production-plans/create': ['production.create'],
  '/dashboard/quality': ['quality.check'],
  '/dashboard/quality-standards': ['quality.check'],
  '/dashboard/quality-standards/create': ['quality.create'],
  '/dashboard/quality-checks': ['quality.check'],
  '/dashboard/quality-checks/create': ['quality.check'],
  '/dashboard/quality-checkpoints': ['quality.check'],
  '/dashboard/quality-checkpoints/create': ['quality.create'],
  '/dashboard/food-samples': ['quality.check'],
  '/dashboard/food-samples/create': ['quality.check'],
  '/dashboard/nutrition-consultations': ['nutrition.consult'],
  '/dashboard/nutrition-consultations/create': ['nutrition.consult'],
  '/dashboard/users': ['users.view'],
  '/dashboard/users/create': ['users.create'],
  '/dashboard/roles': ['system.config'],
  '/dashboard/roles/create': ['system.config'],
  '/dashboard/user-roles': ['users.view'],
  '/dashboard/user-roles/create': ['users.create'],
  '/dashboard/notifications': ['reports.view'],
  '/dashboard/monitoring': ['analytics.view'],
  '/dashboard/monitoring/real-time': ['analytics.view'],
  '/dashboard/monitoring/performance': ['analytics.view'],
  '/dashboard/monitoring/analytics': ['analytics.view'],
  '/dashboard/monitoring/reports': ['reports.view'],
  '/dashboard/analytics': ['analytics.view'],
  '/dashboard/performance': ['analytics.view'],
  '/dashboard/financial': ['finance.view'],
  '/dashboard/financial/transactions': ['finance.view'],
  '/dashboard/financial/transactions/create': ['finance.manage'],
  '/dashboard/financial/budgets/create': ['budget.manage'],
  '/dashboard/feedback': ['feedback.view'],
  '/dashboard/waste-records': ['waste.view'],
  '/dashboard/waste-records/create': ['waste.create'],
  '/dashboard/items': ['inventory.view'],
  '/dashboard/items/create': ['inventory.create'],
  '/dashboard/resource-usage': ['inventory.view'],
  '/dashboard/resource-usage/create': ['inventory.create'],
  '/dashboard/audit-logs': ['audit.view'],
  '/dashboard/system-config': ['system.config'],
  '/dashboard/admin': ['users.view'], // Admin dashboard needs user management permissions
  '/dashboard/admin/users': ['users.view'],
  '/dashboard/admin/settings': ['system.config'],
  '/dashboard/admin/security': ['system.config'],
  '/dashboard/admin/database': ['system.config'],
  '/dashboard/profile': [] // Always accessible to authenticated users
}

// Helper function to get permissions for a given path
export function getPermissionsForPath(path: string): string[] {
  return PERMISSION_MAP[path] || []
}

// Helper function to check if a path requires specific permissions
export function pathRequiresPermissions(path: string): boolean {
  const permissions = getPermissionsForPath(path)
  return permissions.length > 0
}
